#!/bin/bash

# Have location that stores the config files
# 1. create a config
#   prompt for values and save
# view, edit, delete, list, run

# potional:
#     backup config file
# options:
#   -n, --no-dry-run (sync only)
#   -r, --reverse (sync only)
# maybe overrides for backups

# declare TITLE="Example Backup"
# declare DESCRIPTION="This is just an example."
# declare BACKUP_NAME="example_backup"
# declare BACKUP_TYPE="ARCHIVE" # or SYNC
# declare SOURCE="*"
# declare DESTINATION="$HOME/mybackups"
# declare WORKING_PATH="$HOME/Pictures"
# declare EXCLUDE='Screenshots'

ParseArgs() {
    while test $# -gt 0; do
        _KEY="$1"
        case "$_KEY" in
            -n|--no-dry-run)
                DRY_RUN=""
                ;;
            -h|--help)
                Help
                exit 0
                ;;
            -v|--version)
                echo "put version here"
                exit 0
                ;;
            -*|--*)
                echo "Unknown argument: $_KEY"
                exit 1
                ;;
            *)  # One positional, backup file
                BACKUP_CONFIG=$1
                if [ ! -f $BACKUP_CONFIG ]; then
                    echo "Backup configuration file not found: $BACKUP_CONFIG"
                    exit 1
                fi
                ;;
        esac
        shift
    done
}


Help() {
    echo "
Creates a tar.gz backup with date/time in the file name.

    Required Information:
    - included files/dirs       [<BACKUP_NAME>.include]
    - excluded files/dirs       [<BACKUP_NAME>.exclude]
    - destination directory     [export DESTINATION=..]
    - backup name               [argument -n]

    Setup:
        - Create two files with the same prefix
          suffix should be .include and .exclude accordingly
            Ex.
                mybackup.include
                mybackup.exclude
        - Set the destination path
            export DESTINATION=<location to store backups>
            Ex.
                export DESTINATION=\$HOME/mybackups
        - Execute backup with prefix
            Ex.
                backup -n mybackup

    Usage:
        param: [-h] Display this help
        param: [-n] Name of the backup
"
}


ShortHelp() {
    echo "
    Usage:
        backup <arg1, arg2, ..>
    Arguments:
        -h, help
        -n <name>, name of the backup
"
}


CheckInputs() {
    # Validate configuration file inputs
    # Change to working directory if given
    if [ -z $BACKUP_TYPE ]; then
        echo "Error - Missing required backup type"
    else
        if [ $BACKUP_TYPE != "ARCHIVE" ] && [ $BACKUP_TYPE != "SYNC" ]; then
            echo "Error - Invalid backup type: '$BACKUP_TYPE'"
            echo "  Valid types: ARCHIVE or SYNC"
            exit 1
        fi
    fi

    if [ -z "$SOURCE" ]; then
        echo "  Error - Missing required source"
        exit 1
    fi

    if [ -z $DESTINATION ]; then
        echo "Error - Missing required destination"
        exit 1
    elif [ ! -d $DESTINATION ]; then
        echo "  Backup destination does not exist. Attempting to create:"
        echo "    $DESTINATION"
        mkdir -p $DESTINATION
        if [ $? -ne 0 ]; then
            echo "Error - Unable to create destination path: $DESTINATION"
            exit 1
        else
            echo "    Created directory at $DESTINATION"
        fi
    fi

    if [ -z $WORKING_PATH ]; then
        # If no working path, then the source must be an absolute path
        if [ ! -d $SOURCE ]; then
            echo "Error - Source does not exist or is a relative path:"
            echo "  $SOURCE"
            echo "  Either add a working directory or enter an existing source path"
            exit 1
        fi
    else
        # tar --directory or -C does not work when source is a pattern
        cd $WORKING_PATH
    fi
}


ArchiveBackup() {
    echo "Starting archive backup.."
    tar \
        --create \
        --gzip \
        --verbose \
        --file=$BACKUP_PATH \
        --exclude-from=$EXCLUDE_FILE \
        $SOURCE
    if [ $? -eq 0 ]; then
        echo "Backup complete."
        echo "  $BACKUP_PATH"
    else
        echo "Error - creating backup file"
    fi
}


SyncBackup() {
    echo "Starting sync.."
    #rsync -avhn --exclude-from exclude.lst --delete-after /media/orth/backup/Library/ /mnt/shared/Library/ | tee $HOME/Desktop/log.txt
    rsync \
        --archive \
        --delete-after \
        --exclude-from="$EXCLUDE_FILE" \
        --human-readable \
        --verbose \
        $DRY_RUN \
        $SOURCE \
        $DESTINATION \
        | tee $LOG_FILE
    if [ $? -eq 0 ]; then
        echo "Sync complete."
    else
        echo "Error syncing"
        echo "  $SOURCE"
        echo "  $DESTINATION"
    fi
}


#####################################################################
#                                Main                               #
#####################################################################
declare BACKUP_EXT=".tar.gz"
declare DATE_TIME=$(date +"%Y%m%d_%H%M%S")
declare DRY_RUN="--dry-run"

ParseArgs "$@"
echo "Reading configuration file.."
source $BACKUP_CONFIG
CheckInputs
BACKUP_PATH=${DESTINATION}/${BACKUP_NAME}_${DATE_TIME}${BACKUP_EXT}
printf 'Title:\n  %s\n' "$TITLE"
printf 'Description:\n  %s\n' "$DESCRIPTION"

if [ $BACKUP_TYPE = "ARCHIVE" ]; then
    ArchiveBackup
elif [ $BACKUP_TYPE = "SYNC" ]; then
    SyncBackup
else
    echo "Error - Bad backup type: '$BACKUP_TYPE'"
    exit 1
fi

exit 0